### ISSUE TITLE
Eigenes Unterverzeichnis für die Bogen

### ISSUE THREAD

**Issue by cysouw** [engsterhold/wenker-storage#6]
Können wir ein separates Verzeichnis für die Bögen machen? Dann bleiben auf dem Toplevel nur noch `gitignore` und `error.log` übrig. Und dann können wir z.B. einen README.md hinzufügen, und andere Dateien, ohne die Verbindung zur Webseite zu stören

**Comment by engsterhold** [comment]
Kommt, sobald ich ein paar Vorarbeiten getan habe.

**Comment by cysouw** [comment]
@engsterhold glaubst du, du schaffst das noch bevor unser Treffen am Mittwoch?
